# Generated by Django 4.1.4 on 2022-12-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='covers',
            field=models.ImageField(default=1, upload_to='covers/'),
            preserve_default=False,
        ),
    ]
