# Generated by Django 4.1.4 on 2022-12-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_book_writer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='institute',
            field=models.CharField(default=1, max_length=350),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
