# Generated by Django 4.1.4 on 2022-12-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_book_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='covers',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='stars',
            field=models.CharField(choices=[('1', 'خیلی بد'), ('2', 'بد'), ('3', 'متوسط'), ('4', 'خوب'), ('5', 'خیلی خوب')], max_length=15),
        ),
    ]
