# Generated by Django 4.1.4 on 2022-12-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='covers',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
    ]
